guidelines/developer-guides/editing-these-guidelines.rst, tools/requirements.txt
Found a path type and updated the Sphinx version to be up-to-date,
which enabled the HTML build to actually take place.
=> Updated doc guideline development instructions

guidelines/proposal-process/initial-proposal.rst
First swing at "initial-proposal"
=> Initial Proposal

oval-schemas/linux-definitions-schema.xsd, oval-schemas/linux-system-characteristics-schema.xsd
Modified original proposal.  Removed `lsmod` and `modprobe`, replaced with single `kernelmodule` construct.  
The 2nd test in the PR is a new construct, proposing the `sestatus_(test|object|state|item)`.  This test allows implementations to collect and evaluate information stemming from the output of the `sestatus` command.
=> Updated proposal; Add 2 new Linux Tests

oval-schemas/windows-definitions-schema.xsd, oval-schemas/windows-system-characteristics-schema.xsd
Added allowable empty string enumeration value for Entity(State|Item)FileAttributeType, per standard for other OVAL enumeration types.
=> File Attribute Type

oval-schemas/macos-definitions-schema.xsd, oval-schemas/macos-system-characteristics-schema.xsd
Added new OSX pwpolicy-based test to account for new command format (using -getaccountpolicies and XML output) and deprecated options (-getpolicy)
=> Proposal:  Addition of the pwpolicy (5.12) test to Mac OSX schema

.gitignore, guidelines/community-organization/oval-leadership-board.rst
Migrates the relevant/missing MITRE documentation over to our current site for clarity and completeness, without changing any of the missing rules/processes themselves.
See https://github.com/OVAL-Community/OVAL/issues/97
=> Improve OVAL Leadership Board-related process documentation (fixes #97)

oval-schemas/unix-definitions-schema.xsd, oval-schemas/unix-system-characteristics-schema.xsd
Added a new unix sshd test to collect and evaluate named sshd parameters.  Content to follow, and will be added to issue.
=> New Unix SSHD test proposal

oval-schemas/macos-definitions-schema.xsd, oval-schemas/macos-system-characteristics-schema.xsd
Based on some discussions with @solind we decided to narrow the scope of this test to only check for disabled services in the "system" domain, i.e. based on the output of the `launchctl print-disabled system` command.  This eliminated the need for the `domain` element in the object (and state and item) and made the `disabledservice_object` a singleton.
=> Modifications to disabledservice_(test|object|state|item)

oval-schemas/README.md
Having more than one "official" place that contains schemas looks like asking for trouble - when schemas are updated, there is a risk that one of those repositories will fall behind and mislead others.
I have also come across https://github.com/OVALProject/Language/tree/master/docs that contains human-readable OVAL schema  documentation in form of Markdown files that is extracted from XSDs. What is the relation of the OVALProject to CIS/community OVAL repositories?
=> Introduce a schema directory README that points out to oval-community-guidelines.readthedocs.io

oval-schemas/aws-definitions-schema.xsd, oval-schemas/aws-system-characteristics-schema.xsd, oval-schemas/independent-definitions-schema.xsd, oval-schemas/independent-system-characteristics-schema.xsd, oval-schemas/oval-common-schema.xsd
This PR represents the addition of a new schema applicable to the collection and evaluation of AWS environments using their respective API.
The current proposal includes an enumeration for the various AWS services that may be queried using the API/SDK/CLI. I am not married to the idea that this element needs to be an enumeration, as the list services changes/expands/evolves rapidly. If this element is changed to a simple Entity(Object|State|Item)StringType, I am fine with that, and can include documentation that if a service is incorrect or unavailable, that some sort of error should occur (maybe an item status="error" or similar).
This PR includes 3 test/obj/state constructs:
- api_test: The API test allows for the invocation of the AWS API for those operations that return JSON content, …
=> AWS Schemas, Take 5

guidelines/index.rst
@solind point oval board link correctly since CIS nuked the static site
=> Issue 136: Update index.rst

oval-schemas/aix-definitions-schema.xsd, oval-schemas/aix-system-characteristics-schema.xsd
A number of recommendations in CIS benchmarks deal with the collection and evaluation of AIX security parameters. This proposal adds the lssec_(test|object|state|item) constructs, allowing for the collection and evaluation of these parameter values.
This construct is based on the invocation and evaluation of the `lssec` command for AIX, documented [HERE](https://www.ibm.com/docs/en/aix/7.1?topic=l-lssec-command).
=> Proposal to add new constructs to AIX schema

oval-schemas/windows-definitions-schema.xsd, oval-schemas/windows-system-characteristics-schema.xsd
Un-deprecated trusteename from windows file/registry permissions/audit items
Added user/group back to user_sid_item and group_sid_item
=> Adding trustee_name back to several windows test states and items

oval-schemas/oval-definitions-schema.xsd
Adding a merge function which joins together multiple elements into a single variable, with an optional delimiter, and optional sorting.  Had to add a new sort enumeration which may need to be discussed.
=> Add Merge function type and sort enumeration

.github/workflows/clean_for_release.yaml
First proposal of the actions used to clean and provide a release branch for the repository.
=> Add github actions to clean and release

.github/workflows/buildRelease.yml
Adding a GH workflow for which is triggered by publishing/editing a release (ie, via [the creation of a new release](https://github.com/OVAL-Community/OVAL/releases/new)) will attach the schema files to the release asset list as per the example in the below screenshot.  In the future this can be updated to build and attach other artifacts to the asset list, as it contains a placeholder for where that would be done.
=> Adding GH Action to attached schema files to GH release asset list

oval-schemas/independent-definitions-schema.xsd, oval-schemas/independent-system-characteristics-schema.xsd
Attached are sample results from the SCC application, which has implemented this test.  
[SQL512_Sample_Results.zip](https://github.com/user-attachments/files/17396752/SQL512_Sample_Results.zip)
These results are from a SCAP datastream, and contain more than SQL512 tests, but there are plenty of SQL512 tests to demonstrate it's functionality.  
This method is generating results for the entire host.  IF/when SCAP 3.0 implements a 'target' method, results could then be generated based on host/instance/database.
=> Added sql512 and deprecated sql57 based on #153

oval-schemas/aix-definitions-schema.xsd, oval-schemas/android-definitions-schema.xsd, oval-schemas/apple-ios-definitions-schema.xsd, oval-schemas/asa-definitions-schema.xsd, oval-schemas/catos-definitions-schema.xsd, oval-schemas/esx-definitions-schema.xsd, oval-schemas/freebsd-definitions-schema.xsd, oval-schemas/hpux-definitions-schema.xsd, oval-schemas/independent-definitions-schema.xsd, oval-schemas/ios-definitions-schema.xsd, oval-schemas/iosxe-definitions-schema.xsd, oval-schemas/junos-definitions-schema.xsd, oval-schemas/linux-definitions-schema.xsd, oval-schemas/macos-definitions-schema.xsd, oval-schemas/netconf-definitions-schema.xsd, oval-schemas/pixos-definitions-schema.xsd, oval-schemas/sharepoint-definitions-schema.xsd, oval-schemas/solaris-definitions-schema.xsd, oval-schemas/unix-definitions-schema.xsd, oval-schemas/windows-definitions-schema.xsd
This pull request is pending additional feedback from OVAL consumers.  Will be decided and merged in after 11-07-2024
=> Deprecated 122 oval tests with no documented usage

oval-schemas/independent-definitions-schema.xsd, oval-schemas/independent-system-characteristics-schema.xsd
This pull request adds the capability discussed in #150
=> Add new independent test to support running shell commands called shellcommand

oval-schemas/oval-system-characteristics-schema.xsd
Modified the 'type' for the 'ip_address' element in an interface from 'xsd:string' to oval-sc:EntityItemIPAddressType'.  This entity type already contains the needed 'datatype' attribute.
@solind, John @johnulmer-oval is out of the office for the week, and in my review of his update I'm wondering if he missed adding a maxoccurs=unbounded?  Can you review this change, (and the original issue #134) to see if I should be adding that for this merge?
=> Update ip address field to use IPAddressType to include ipv4 vs ipv6 data

oval-schemas/windows-definitions-schema.xsd, oval-schemas/windows-system-characteristics-schema.xsd
Added clarity to all of the password policy items, providing the exact name of the element matching MS documentation.
=> Added alternate name from MS documentation for all password policy items

.github/workflows/buildRelease.yml, .gitignore, GNUmakefile, rsrc/index.html, tools/oval_xsd2html.xsl
This workflow creates a 2 zip file (one for the OVAL schemas, and another for the OVAL HTML docs) and attaches them to the Release in GitHub.
See the [Adam 5.13.0 Build Pipeline Test](https://github.com/A-Biggs/OVAL/releases/tag/Adam5.13.0Test) at https://github.com/A-Biggs/OVAL/releases for an example of what is generated by this workflow for a release.
`<a href="http://oval.cisecurity.org/terms">OVAL Terms of Use</a>` should be updated in the rsrc/index.html file with a new link as that one is currently broken.
=> Updated build workflow for releases

guidelines/oval-schema-documentation/unix-definitions-schema.rst, guidelines/oval-schema-documentation/windows-definitions-schema.rst
Found a workaround in our rst files to make internal links have _unix in them which prevents a bug in the processing of the files
=> Fixed readthedocs cross wiring of unix/windows tests that have the same name

oval-schemas/kubernetes-definitions-schema.xsd, oval-schemas/kubernetes-system-characteristics-schema.xsd
Added schema based on CIS extension, updated to OVAL 6.0 namespaces, dates, and license
=> Add kubernetes schema based on CIS OVAL extension

oval-schemas/oval-definitions-schema.xsd
Committing the addition of the new encapsulated_definition and  EncapsulatedDefinitionType to preserve work and allow review.
Remaining to be addressed.
1 - In the EncapsulatedDefinitionType, the 'xsd:unique name="UniqueAffectedFamily"' is commented out.  Need to figure out best way to enforce this requirement. 2 - Review that modified 'testKeyRef' checks are appropriate.
=> Update oval-definitions-schema.xsd to support encapsulated definitions along with 5.8 style defintitions

oval-schemas/aix-definitions-schema.xsd, oval-schemas/aix-system-characteristics-schema.xsd, oval-schemas/solaris-definitions-schema.xsd, oval-schemas/solaris-system-characteristics-schema.xsd
Due to documented usage from SecPod
=> Added AIX interim_fix, os_level tests and Solaris package, package511 and patch54 tests back to OVAL 6

oval-schemas/independent-definitions-schema.xsd
The 'command' of the test is intended to be a literal executable/binary, or a one-liner where data from one or more executables is manipulated and the intended text is printed to standard out.
=> Updated shellcommand documentation to make it clear that the 'command' is not a script

oval-schemas/independent-definitions-schema.xsd
=> Updated documentation to explain that shellcommand 'command' does not mean a multi-line script

rsrc/index.html
Need to update before the OVAL 6.0 release, as this file is not programmatically generated.
=> Removed platforms from offline HTML documentation that have been removed in OVAL 6

oval-schemas/windows-definitions-schema.xsd, oval-schemas/windows-system-characteristics-schema.xsd
In order to maintain functionality from OVAL 5.11.2, these elements are needed, as we dropped the windows user test
=> Resolved #242 by adding full_name, comment and password_age_days to user_sid55 state and item

guidelines/index.rst, oval-schemas/independent-definitions-schema.xsd
Trivial change, minOccurs = 0 for 'command' on state
=> OVAL 5.12.1 update independent shellcommand state  command to have minoccurs 0

oval-schemas/windows-definitions-schema.xsd, oval-schemas/windows-system-characteristics-schema.xsd
Added element per discussions with @solind
=> Added days_since_last_logon attribute to resolve #221

oval-schemas/windows-definitions-schema.xsd, oval-schemas/windows-system-characteristics-schema.xsd
I've made a bit of a mess of this issue, accidentally committing it originally to master (back in March), then reverting and adding to the 6.0.1 dev branch, and now that OVAL 5.12.1 appears to be aligning with SCAP 1.4, I'm re-adding this update back to 5.12.1.  OVAL developers should still refrain from using the deprecated Windows 'user' test, so these new attributes on user_sid55 are still very useful, and will help the transition to 6.0 eventually.
This PR was originally reviewed and accepted by @solind, but I'd like another sanity check on it, as it will be going directly and intentionally into 'master' as I've already merged 5.12.1_dev into master.
=> Resolved #242 in OVAL 5.12.1 by adding full_name, comment and password_age_days to user_sid55 state and item""
